### ISSUE TITLE
Provide documentation on schema for background worker

### ISSUE THREAD

**Issue by ramiroJCB** [mergestat/sqlq#3]
JLo (@amenowanna) to provide more details on the schema [in this notion document](https://www.notion.so/mergestat/55af9b4d3b584395ad6d0e914df75cd2). Certain aspects like _soft-delete_, `uuid` vs `bigint`, etc. need to be discussed and documented.

**Comment by amenowanna** [comment]
We have added more documentation and will need to keep adding. @riyaz-ali the main doc we are missing from you is your perspective on enums.
